version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=marddb
      - JWT_SECRET=123
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mard_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=marddb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
